name = "Create Fully Loaded"
author = "Unappendixed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82f1884f8736c4d37e293413961d893a262f643954bf65040c352aa1860d83d4"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"
