name = "Create: Fully Loaded"
author = "Unappendixed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94826fd344e4a3ddb586d834664556586c6fa38df3a959d8cfd3ea35af1e5832"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.146"
