name = "Create: Fully Loaded"
author = "Unappendixed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b27d9e21bf7dc4b878562e7afa3b6582e2db7194434728078954678089bc0577"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.146"
