name = "Create Fully Loaded"
author = "Unappendixed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f8672c1e3144fb7b0f7c7e64fbd7a654e727300880d0b302ff6bce05bd1f828"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"
