name = "Create Fully Loaded"
author = "Unappendixed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd3e8a687e4fbd1df0eeb60a2b8374f63a48988684cd3d32f3b3f8b3ff26f58c"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"
