name = "Create Fully Loaded"
author = "Unappendixed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72f80ccfc23f35bd18fa05e1a6a844a129e79e3797cf9427f7fbeebfad973d9f"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"
