name: Create release
on: 
  push:
    tags:
      - '*'
jobs:
  Create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up GOBIN and PATh
        run: |
          echo "GOBIN=${HOME}/go/bin" >> "$GITHUB_ENV"
          echo "${HOME}/go/bin" >> "$GITHUB_PATH"

      - name: Install packwiz tool
        run: 'go install github.com/packwiz/packwiz@latest'

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Run packwiz export tool
        run: 'packwiz curseforge export -o "Create: Fully Loaded - ${{ github.ref_name }}"'

      - name: Attach release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
